export const TIMEZONES = [
    { value: 'Etc/GMT+12', label: '(GMT-12:00) International Date Line West' },
    { value: 'Pacific/Pago_Pago', label: '(GMT-11:00) American Samoa' },
    { value: 'Pacific/Midway', label: '(GMT-11:00) Midway Island' },
    { value: 'Pacific/Honolulu', label: '(GMT-10:00) Hawaii' },
    { value: 'America/Anchorage', label: '(GMT-09:00) Alaska' },
    { value: 'America/Los_Angeles', label: '(GMT-08:00) Pacific Time (US & Canada)' },
    { value: 'America/Tijuana', label: '(GMT-08:00) Tijuana' },
    { value: 'America/Phoenix', label: '(GMT-07:00) Arizona' },
    { value: 'America/Denver', label: '(GMT-07:00) Mountain Time (US & Canada)' },
    { value: 'America/Chihuahua', label: '(GMT-07:00) Mazatlan' },
    { value: 'America/Guatemala', label: '(GMT-06:00) Central America' },
    { value: 'America/Chicago', label: '(GMT-06:00) Central Time (US & Canada)' },
    { value: 'America/Mexico_City', label: '(GMT-06:00) Mexico City' },
    { value: 'America/Monterrey', label: '(GMT-06:00) Monterrey' },
    { value: 'America/Bogota', label: '(GMT-05:00) Bogota' },
    { value: 'America/New_York', label: '(GMT-05:00) Eastern Time (US & Canada)' },
    { value: 'America/Indiana/Indianapolis', label: '(GMT-05:00) Indiana (East)' },
    { value: 'America/Lima', label: '(GMT-05:00) Lima' },
    { value: 'America/Quito', label: '(GMT-05:00) Quito' },
    { value: 'America/Asuncion', label: '(GMT-04:00) Asuncion' },
    { value: 'America/Halifax', label: '(GMT-04:00) Atlantic Time (Canada)' },
    { value: 'America/Caracas', label: '(GMT-04:00) Caracas' },
    { value: 'America/Guyana', label: '(GMT-04:00) Georgetown' },
    { value: 'America/La_Paz', label: '(GMT-04:00) La Paz' },
    { value: 'America/Puerto_Rico', label: '(GMT-04:00) Puerto Rico' },
    { value: 'America/Santiago', label: '(GMT-04:00) Santiago' },
    { value: 'America/St_Johns', label: '(GMT-03:30) Newfoundland' },
    { value: 'America/Sao_Paulo', label: '(GMT-03:00) Brasilia' },
    { value: 'America/Argentina/Buenos_Aires', label: '(GMT-03:00) Buenos Aires' },
    { value: 'America/Montevideo', label: '(GMT-03:00) Montevideo' },
    { value: 'Atlantic/South_Georgia', label: '(GMT-02:00) Greenland' },
    { value: 'Etc/GMT+2', label: '(GMT-02:00) Mid-Atlantic' },
    { value: 'Atlantic/Azores', label: '(GMT-01:00) Azores' },
    { value: 'Atlantic/Cape_Verde', label: '(GMT-01:00) Cape Verde Is.' },
    { value: 'Europe/London', label: '(GMT+00:00) London' },
    { value: 'Europe/Edinburgh', label: '(GMT+00:00) Edinburgh' },
    { value: 'Europe/Lisbon', label: '(GMT+00:00) Lisbon' },
    { value: 'Africa/Monrovia', label: '(GMT+00:00) Monrovia' },
    { value: 'UTC', label: '(GMT+00:00) UTC' },
    { value: 'Europe/Amsterdam', label: '(GMT+01:00) Amsterdam' },
    { value: 'Europe/Belgrade', label: '(GMT+01:00) Belgrade' },
    { value: 'Europe/Berlin', label: '(GMT+01:00) Berlin' },
    { value: 'Europe/Paris', label: '(GMT+01:00) Paris' },
    { value: 'Europe/Madrid', label: '(GMT+01:00) Madrid' },
    { value: 'Europe/Rome', label: '(GMT+01:00) Rome' },
    { value: 'Europe/Vienna', label: '(GMT+01:00) Vienna' },
    { value: 'Europe/Zurich', label: '(GMT+01:00) Zurich' },
    { value: 'Europe/Prague', label: '(GMT+01:00) Prague' },
    { value: 'Europe/Stockholm', label: '(GMT+01:00) Stockholm' },
    { value: 'Europe/Warsaw', label: '(GMT+01:00) Warsaw' },
    { value: 'Europe/Kaliningrad', label: '(GMT+02:00) Kaliningrad' },
    { value: 'Europe/Athens', label: '(GMT+02:00) Athens' },
    { value: 'Europe/Bucharest', label: '(GMT+02:00) Bucharest' },
    { value: 'Africa/Cairo', label: '(GMT+02:00) Cairo' },
    { value: 'Europe/Helsinki', label: '(GMT+02:00) Helsinki' },
    { value: 'Europe/Istanbul', label: '(GMT+03:00) Istanbul' },
    { value: 'Europe/Moscow', label: '(GMT+03:00) Moscow' },
    { value: 'Asia/Dhaka', label: '(GMT+06:00) Dhaka' },
    { value: 'Asia/Kolkata', label: '(GMT+05:30) Kolkata' },
    { value: 'Asia/Kathmandu', label: '(GMT+05:45) Kathmandu' },
    { value: 'Asia/Bangkok', label: '(GMT+07:00) Bangkok' },
    { value: 'Asia/Tokyo', label: '(GMT+09:00) Tokyo' },
    { value: 'Australia/Sydney', label: '(GMT+10:00) Sydney' },
    { value: 'Pacific/Auckland', label: '(GMT+12:00) Auckland' }
]