/**
 * Draft service.
 *
 * Per-user, per-context auto-save for the rich text editor (Basecamp-style).
 * Used by useDraftPersistence composable, which debounces editor updates and
 * fires these calls behind the scenes.
 *
 * The context_key encodes (resource, id, field) tuples generated by parent
 * components — e.g. "task:5:comment:new", "comment:42:edit". The backend
 * validates the shape, so callers can pass it through opaquely.
 */

import axios from '@/axios'

const url = (key) => `/api/drafts/${encodeURIComponent(key)}`

export async function fetchDraft(contextKey, { signal } = {}) {
	try {
		const { data } = await axios.get(url(contextKey), { signal })
		return data // { content, attachment_ids, updated_at }
	} catch (e) {
		if (e?.response?.status === 404) return null
		throw e
	}
}

export async function saveDraft(contextKey, content, { signal } = {}) {
	await axios.put(url(contextKey), { content }, { signal })
}

export async function deleteDraft(contextKey, { signal } = {}) {
	await axios.delete(url(contextKey), { signal })
}
