<script setup>
import { ref, computed, onMounted } from 'vue'

const categories = [
	{
		name: 'Smileys', icon: '😀',
		emojis: [
			{ emoji: '😀', name: 'grinning face' },
			{ emoji: '😃', name: 'grinning face with big eyes' },
			{ emoji: '😄', name: 'grinning face with smiling eyes' },
			{ emoji: '😁', name: 'beaming face with smiling eyes' },
			{ emoji: '😆', name: 'grinning squinting face' },
			{ emoji: '😅', name: 'grinning face with sweat' },
			{ emoji: '🤣', name: 'rolling on the floor laughing' },
			{ emoji: '😂', name: 'face with tears of joy' },
			{ emoji: '🙂', name: 'slightly smiling face' },
			{ emoji: '🙃', name: 'upside down face' },
			{ emoji: '😉', name: 'winking face' },
			{ emoji: '😊', name: 'smiling face with smiling eyes' },
			{ emoji: '😇', name: 'smiling face with halo' },
			{ emoji: '🥰', name: 'smiling face with hearts' },
			{ emoji: '😍', name: 'smiling face with heart eyes' },
			{ emoji: '🤩', name: 'star struck' },
			{ emoji: '😘', name: 'face blowing a kiss' },
			{ emoji: '😋', name: 'face savoring food' },
			{ emoji: '😜', name: 'winking face with tongue' },
			{ emoji: '🤪', name: 'zany face' },
			{ emoji: '🤑', name: 'money mouth face' },
			{ emoji: '🤗', name: 'smiling face with open hands' },
			{ emoji: '🤭', name: 'face with hand over mouth' },
			{ emoji: '🤫', name: 'shushing face' },
			{ emoji: '🤔', name: 'thinking face' },
			{ emoji: '🤐', name: 'zipper mouth face' },
			{ emoji: '🤨', name: 'face with raised eyebrow' },
			{ emoji: '😐', name: 'neutral face' },
			{ emoji: '😑', name: 'expressionless face' },
			{ emoji: '😶', name: 'flushed face' },
			{ emoji: '😏', name: 'smirking face' },
			{ emoji: '😒', name: 'unamused face' },
			{ emoji: '🙄', name: 'face with rolling eyes' },
			{ emoji: '😬', name: 'grimacing face' },
			{ emoji: '😌', name: 'relieved face' },
			{ emoji: '😔', name: 'pensive face' },
			{ emoji: '😪', name: 'sleepy face' },
			{ emoji: '😴', name: 'sleeping face' },
			{ emoji: '😷', name: 'face with mouth covered' },
			{ emoji: '🤒', name: 'face with thermometer' },
			{ emoji: '🤕', name: 'face with head bandage' },
			{ emoji: '🤢', name: 'nauseated face' },
			{ emoji: '🤮', name: 'face vomiting' },
			{ emoji: '🤧', name: 'sneezing face' },
			{ emoji: '🥵', name: 'hot face' },
			{ emoji: '🥶', name: 'cold face' },
			{ emoji: '🥴', name: 'woozy face' },
			{ emoji: '😵', name: 'dizzy face' },
			{ emoji: '🤯', name: 'exploding head' },
			{ emoji: '🥳', name: 'partying face' },
			{ emoji: '😎', name: 'smiling face with sunglasses' },
			{ emoji: '🤓', name: 'nerd face' },
			{ emoji: '😕', name: 'confused face' },
			{ emoji: '😟', name: 'worried face' },
			{ emoji: '🙁', name: 'slightly frowning face' },
			{ emoji: '☹️', name: 'frowning face' },
			{ emoji: '😮', name: 'face with open mouth' },
			{ emoji: '😲', name: 'astonished face' },
			{ emoji: '😳', name: 'flushed face' },
			{ emoji: '🥺', name: 'pleading face' },
			{ emoji: '😦', name: 'frowning face with open mouth' },
			{ emoji: '😧', name: 'anguished face' },
			{ emoji: '😨', name: 'fearful face' },
			{ emoji: '😰', name: 'anxious face with sweat' },
			{ emoji: '😥', name: 'sad but relieved face' },
			{ emoji: '😢', name: 'crying face' },
			{ emoji: '😭', name: 'loudly crying face' },
			{ emoji: '😱', name: 'face screaming in fear' },
			{ emoji: '😖', name: 'confounded face' },
			{ emoji: '😣', name: 'persevering face' },
			{ emoji: '😞', name: 'disappointed face' },
			{ emoji: '😓', name: 'downturned face with sweat' },
			{ emoji: '😩', name: 'weary face' },
			{ emoji: '😫', name: 'tired face' },
			{ emoji: '🥱', name: 'yawning face' },
			{ emoji: '😤', name: 'face with steam from nose' },
			{ emoji: '😡', name: 'pouting face' },
			{ emoji: '😠', name: 'angry face' },
			{ emoji: '🤬', name: 'face with symbols on mouth' },
			{ emoji: '😈', name: 'smiling face with horns' },
			{ emoji: '👿', name: 'angry face with horns' },
			{ emoji: '💀', name: 'skull' },
			{ emoji: '☠️', name: 'skull and crossbones' },
			{ emoji: '💩', name: 'pile of poo' },
			{ emoji: '🤡', name: 'clown face' },
			{ emoji: '👹', name: 'ogre' },
			{ emoji: '👺', name: 'goblin' },
			{ emoji: '👻', name: 'ghost' },
			{ emoji: '👽', name: 'alien' },
			{ emoji: '👾', name: 'alien monster' },
			{ emoji: '🤖', name: 'robot' },
		],
	},
	{
		name: 'People', icon: '👋',
		emojis: [
			{ emoji: '👋', name: 'waving hand' },
			{ emoji: '🤚', name: 'raised back of hand' },
			{ emoji: '🖐️', name: 'hand with fingers splayed' },
			{ emoji: '✋', name: 'raised hand' },
			{ emoji: '🖖', name: 'vulcan salute' },
			{ emoji: '👌', name: 'ok hand' },
			{ emoji: '🤌', name: 'pinched fingers' },
			{ emoji: '✌️', name: 'victory hand' },
			{ emoji: '🤞', name: 'crossed fingers' },
			{ emoji: '🤟', name: 'love you gesture' },
			{ emoji: '🤘', name: 'sign of the horns' },
			{ emoji: '🤙', name: 'call me hand' },
			{ emoji: '👈', name: 'backhand index pointing left' },
			{ emoji: '👉', name: 'backhand index pointing right' },
			{ emoji: '👆', name: 'backhand index pointing up' },
			{ emoji: '👇', name: 'backhand index pointing down' },
			{ emoji: '☝️', name: 'index pointing up' },
			{ emoji: '👍', name: 'thumbs up' },
			{ emoji: '👎', name: 'thumbs down' },
			{ emoji: '✊', name: 'raised fist' },
			{ emoji: '👊', name: 'oncoming fist' },
			{ emoji: '🤛', name: 'left facing fist' },
			{ emoji: '🤜', name: 'right facing fist' },
			{ emoji: '👏', name: 'clapping hands' },
			{ emoji: '🙌', name: 'raising hands' },
			{ emoji: '🫶', name: 'heart hands' },
			{ emoji: '👐', name: 'open hands' },
			{ emoji: '🤲', name: 'open hands with fingers splayed' },
			{ emoji: '🤝', name: 'handshake' },
			{ emoji: '🙏', name: 'folded hands' },
			{ emoji: '✍️', name: 'writing hand' },
			{ emoji: '💅', name: 'nail polish' },
			{ emoji: '💪', name: 'flexed biceps' },
			{ emoji: '🦾', name: 'mechanical arm' },
			{ emoji: '🦵', name: 'leg' },
			{ emoji: '🦶', name: 'foot' },
			{ emoji: '👀', name: 'eyes' },
			{ emoji: '👁️', name: 'eye' },
			{ emoji: '👅', name: 'tongue' },
			{ emoji: '👄', name: 'mouth' },
			{ emoji: '💋', name: 'kiss mark' },
			{ emoji: '👤', name: 'bust in silhouette' },
			{ emoji: '👥', name: 'busts in silhouette' },
			{ emoji: '🫂', name: 'people hugging' },
			{ emoji: '🧑', name: 'person' },
			{ emoji: '👦', name: 'boy' },
			{ emoji: '👧', name: 'girl' },
			{ emoji: '👨', name: 'man' },
			{ emoji: '👩', name: 'woman' },
			{ emoji: '🧓', name: 'older person' },
			{ emoji: '👴', name: 'old man' },
			{ emoji: '👵', name: 'old woman' },
			{ emoji: '👶', name: 'baby' },
			{ emoji: '🧒', name: 'child' },
			{ emoji: '👼', name: 'baby angel' },
			{ emoji: '🎅', name: 'santa' },
			{ emoji: '🤶', name: 'mrs claus' },
			{ emoji: '🦸', name: 'superhero' },
			{ emoji: '🦹', name: 'supervillain' },
			{ emoji: '🧙', name: 'mage' },
			{ emoji: '🧚', name: 'fairy' },
			{ emoji: '🧛', name: 'vampire' },
			{ emoji: '🧜', name: 'person taking bath' },
			{ emoji: '🧝', name: 'elf' },
			{ emoji: '🧞', name: 'genie' },
			{ emoji: '🧟', name: 'zombie' },
			{ emoji: '🧌', name: 'troll' },
		],
	},
	{
		name: 'Nature', icon: '🌸',
		emojis: [
			{ emoji: '🌸', name: 'cherry blossom' },
			{ emoji: '🌺', name: 'hibiscus' },
			{ emoji: '🌻', name: 'sunflower' },
			{ emoji: '🌹', name: 'rose' },
			{ emoji: '🌷', name: 'tulip' },
			{ emoji: '🌼', name: 'blossom' },
			{ emoji: '💐', name: 'bouquet' },
			{ emoji: '🍀', name: 'four leaf clover' },
			{ emoji: '☘️', name: 'shamrock' },
			{ emoji: '🌿', name: 'herb' },
			{ emoji: '🍃', name: 'leaf fluttering in wind' },
			{ emoji: '🍂', name: 'fallen leaf' },
			{ emoji: '🍁', name: 'maple leaf' },
			{ emoji: '🌱', name: 'seedling' },
			{ emoji: '🌲', name: 'evergreen tree' },
			{ emoji: '🌳', name: 'deciduous tree' },
			{ emoji: '🌴', name: 'palm tree' },
			{ emoji: '🌵', name: 'cactus' },
			{ emoji: '🌾', name: 'sheaf of rice' },
			{ emoji: '🍄', name: 'mushroom' },
			{ emoji: '🌰', name: 'chestnut' },
			{ emoji: '🐶', name: 'dog face' },
			{ emoji: '🐱', name: 'cat face' },
			{ emoji: '🐭', name: 'mouse face' },
			{ emoji: '🐹', name: 'hamster' },
			{ emoji: '🐰', name: 'rabbit' },
			{ emoji: '🦊', name: 'fox' },
			{ emoji: '🐻', name: 'bear' },
			{ emoji: '🐼', name: 'panda' },
			{ emoji: '🐨', name: 'koala' },
			{ emoji: '🐯', name: 'tiger face' },
			{ emoji: '🦁', name: 'lion' },
			{ emoji: '🐮', name: 'cow face' },
			{ emoji: '🐷', name: 'pig face' },
			{ emoji: '🐸', name: 'frog' },
			{ emoji: '🐵', name: 'monkey face' },
			{ emoji: '🐔', name: 'chicken' },
			{ emoji: '🐧', name: 'penguin' },
			{ emoji: '🐦', name: 'bird' },
			{ emoji: '🦆', name: 'duck' },
			{ emoji: '🦅', name: 'eagle' },
			{ emoji: '🦉', name: 'owl' },
			{ emoji: '🦇', name: 'bat' },
			{ emoji: '🐺', name: 'wolf' },
			{ emoji: '🐗', name: 'boar' },
			{ emoji: '🦄', name: 'unicorn' },
			{ emoji: '🐝', name: 'honeybee' },
			{ emoji: '🦋', name: 'butterfly' },
			{ emoji: '🐛', name: 'bug' },
			{ emoji: '🐌', name: 'snail' },
			{ emoji: '🐞', name: 'lady beetle' },
			{ emoji: '🐜', name: 'ant' },
			{ emoji: '🦟', name: 'mosquito' },
			{ emoji: '🦗', name: 'cricket' },
			{ emoji: '🦎', name: 'lizard' },
			{ emoji: '🐍', name: 'snake' },
			{ emoji: '🐢', name: 'turtle' },
			{ emoji: '🐙', name: 'octopus' },
			{ emoji: '🦑', name: 'squid' },
			{ emoji: '🦞', name: 'lobster' },
			{ emoji: '🦀', name: 'crab' },
			{ emoji: '🐡', name: 'blowfish' },
			{ emoji: '🐠', name: 'tropical fish' },
			{ emoji: '🐟', name: 'fish' },
			{ emoji: '🐬', name: 'dolphin' },
			{ emoji: '🐳', name: 'whale' },
			{ emoji: '🐋', name: 'whale' },
			{ emoji: '🦈', name: 'shark' },
			{ emoji: '🦭', name: 'seal' },
			{ emoji: '🐊', name: 'crocodile' },
			{ emoji: '⭐', name: 'star' },
			{ emoji: '🌙', name: 'moon' },
			{ emoji: '☀️', name: 'sun' },
			{ emoji: '🌈', name: 'rainbow' },
			{ emoji: '❄️', name: 'snowflake' },
			{ emoji: '🔥', name: 'fire' },
			{ emoji: '💧', name: 'water droplet' },
			{ emoji: '🌊', name: 'water wave' },
			{ emoji: '🌍', name: 'globe' },
			{ emoji: '🌎', name: 'globe americas' },
			{ emoji: '🌏', name: 'globe asia' },
		],
	},
	{
		name: 'Food', icon: '🍕',
		emojis: [
			{ emoji: '🍕', name: 'pizza' },
			{ emoji: '🍔', name: 'hamburger' },
			{ emoji: '🍟', name: 'french fries' },
			{ emoji: '🌭', name: 'hot dog' },
			{ emoji: '🥪', name: 'sandwich' },
			{ emoji: '🌮', name: 'taco' },
			{ emoji: '🌯', name: 'burrito' },
			{ emoji: '🥙', name: 'stuffed flatbread' },
			{ emoji: '🥗', name: 'green salad' },
			{ emoji: '🍿', name: 'popcorn' },
			{ emoji: '🥞', name: 'pancakes' },
			{ emoji: '🧇', name: 'waffle' },
			{ emoji: '🥓', name: 'bacon' },
			{ emoji: '🥚', name: 'egg' },
			{ emoji: '🍳', name: 'cooking' },
			{ emoji: '🥘', name: 'paella' },
			{ emoji: '🍲', name: 'pot of food' },
			{ emoji: '🍱', name: 'bento box' },
			{ emoji: '🍣', name: 'sushi' },
			{ emoji: '🍤', name: 'shrimp' },
			{ emoji: '🍙', name: 'rice ball' },
			{ emoji: '🍚', name: 'cooked rice' },
			{ emoji: '🍛', name: 'curry rice' },
			{ emoji: '🍜', name: 'steaming bowl' },
			{ emoji: '🍝', name: 'spaghetti' },
			{ emoji: '🍠', name: 'roasted sweet potato' },
			{ emoji: '🍢', name: 'oden' },
			{ emoji: '🍡', name: 'dango' },
			{ emoji: '🥟', name: 'dumpling' },
			{ emoji: '🥠', name: 'fortune cookie' },
			{ emoji: '🥡', name: 'takeout box' },
			{ emoji: '🦪', name: 'oyster' },
			{ emoji: '🍦', name: 'soft ice cream' },
			{ emoji: '🍧', name: 'shaved ice' },
			{ emoji: '🍨', name: 'ice cream' },
			{ emoji: '🍩', name: 'doughnut' },
			{ emoji: '🍪', name: 'cookie' },
			{ emoji: '🎂', name: 'birthday cake' },
			{ emoji: '🍰', name: 'shortcake' },
			{ emoji: '🧁', name: 'cupcake' },
			{ emoji: '🥧', name: 'pie' },
			{ emoji: '🍫', name: 'chocolate bar' },
			{ emoji: '🍬', name: 'candy' },
			{ emoji: '🍭', name: 'lollipop' },
			{ emoji: '🍮', name: 'custard' },
			{ emoji: '🍯', name: 'honey pot' },
			{ emoji: '☕', name: 'hot beverage' },
			{ emoji: '🫖', name: 'teapot' },
			{ emoji: '🍵', name: 'teacup without handle' },
			{ emoji: '🧃', name: 'beverage box' },
			{ emoji: '🥤', name: 'cup with straw' },
			{ emoji: '🧋', name: 'bubble tea' },
			{ emoji: '🍺', name: 'beer mug' },
			{ emoji: '🍻', name: 'clinking beer mugs' },
			{ emoji: '🥂', name: 'clinking glasses' },
			{ emoji: '🍷', name: 'wine glass' },
			{ emoji: '🥃', name: 'bowl with spoon' },
			{ emoji: '🍸', name: 'cocktail glass' },
			{ emoji: '🍹', name: 'tropical drink' },
			{ emoji: '🧉', name: 'mate' },
			{ emoji: '🍾', name: 'bottle with popping cork' },
			{ emoji: '🍎', name: 'red apple' },
			{ emoji: '🍊', name: 'orange' },
			{ emoji: '🍋', name: 'lemon' },
			{ emoji: '🍌', name: 'banana' },
			{ emoji: '🍍', name: 'pineapple' },
			{ emoji: '🥭', name: 'mango' },
			{ emoji: '🍑', name: 'peach' },
			{ emoji: '🍒', name: 'cherries' },
			{ emoji: '🍓', name: 'strawberry' },
			{ emoji: '🫐', name: 'blueberries' },
			{ emoji: '🥝', name: 'kiwi fruit' },
			{ emoji: '🍅', name: 'tomato' },
			{ emoji: '🥥', name: 'coconut' },
			{ emoji: '🥑', name: 'avocado' },
			{ emoji: '🥦', name: 'broccoli' },
			{ emoji: '🥕', name: 'carrot' },
			{ emoji: '🌽', name: 'corn' },
			{ emoji: '🥐', name: 'croissant' },
			{ emoji: '🥖', name: 'baguette bread' },
			{ emoji: '🫓', name: 'fondue pot' },
			{ emoji: '🧀', name: 'cheese wedge' },
			{ emoji: '🥨', name: 'pretzel' },
			{ emoji: '🥯', name: 'bagel' },
		],
	},
	{
		name: 'Travel', icon: '✈️',
		emojis: [
			{ emoji: '✈️', name: 'airplane' },
			{ emoji: '🚀', name: 'rocket' },
			{ emoji: '🛸', name: 'flying saucer' },
			{ emoji: '🚁', name: 'helicopter' },
			{ emoji: '⛵', name: 'sailboat' },
			{ emoji: '🚢', name: 'ship' },
			{ emoji: '🛳️', name: 'cruise ship' },
			{ emoji: '🚂', name: 'locomotive' },
			{ emoji: '🚆', name: 'train' },
			{ emoji: '🚇', name: 'metro' },
			{ emoji: '🚊', name: 'tram' },
			{ emoji: '🚝', name: 'mountain cableway' },
			{ emoji: '🚞', name: 'mountain railway' },
			{ emoji: '🚌', name: 'bus' },
			{ emoji: '🚍', name: 'oncoming bus' },
			{ emoji: '🚎', name: 'trolleybus' },
			{ emoji: '🚐', name: 'minibus' },
			{ emoji: '🚑', name: 'ambulance' },
			{ emoji: '🚒', name: 'fire engine' },
			{ emoji: '🚓', name: 'police car' },
			{ emoji: '🚕', name: 'taxi' },
			{ emoji: '🚗', name: 'automobile' },
			{ emoji: '🚙', name: 'sport utility vehicle' },
			{ emoji: '🚚', name: 'delivery truck' },
			{ emoji: '🚛', name: 'articulated lorry' },
			{ emoji: '🚜', name: 'tractor' },
			{ emoji: '🏎️', name: 'racing car' },
			{ emoji: '🏍️', name: 'motorcycle' },
			{ emoji: '🛵', name: 'motor scooter' },
			{ emoji: '🚲', name: 'bicycle' },
			{ emoji: '🛴', name: 'kick scooter' },
			{ emoji: '🛹', name: 'skateboard' },
			{ emoji: '🗺️', name: 'world map' },
			{ emoji: '🧭', name: 'compass' },
			{ emoji: '🏔️', name: 'mountain' },
			{ emoji: '⛰️', name: 'mountain' },
			{ emoji: '🌋', name: 'volcano' },
			{ emoji: '🏕️', name: 'camping' },
			{ emoji: '🏖️', name: 'beach with umbrella' },
			{ emoji: '🏜️', name: 'desert' },
			{ emoji: '🏝️', name: 'desert island' },
			{ emoji: '🏟️', name: 'stadium' },
			{ emoji: '🏛️', name: 'classical building' },
			{ emoji: '🏗️', name: 'building construction' },
			{ emoji: '🏘️', name: 'houses' },
			{ emoji: '🏠', name: 'house' },
			{ emoji: '🏡', name: 'house with garden' },
			{ emoji: '🏢', name: 'office building' },
			{ emoji: '🏣', name: 'japanese post office' },
			{ emoji: '🏤', name: 'european post office' },
			{ emoji: '🏥', name: 'hospital' },
			{ emoji: '🏦', name: 'bank' },
			{ emoji: '🏨', name: 'hotel' },
			{ emoji: '🏩', name: 'love hotel' },
			{ emoji: '🏪', name: 'convenience store' },
			{ emoji: '🏫', name: 'school' },
			{ emoji: '🏬', name: 'department store' },
			{ emoji: '🏭', name: 'factory' },
			{ emoji: '🗼', name: 'tokyo tower' },
			{ emoji: '🗽', name: 'statue of liberty' },
			{ emoji: '⛪', name: 'church' },
			{ emoji: '🕌', name: 'mosque' },
			{ emoji: '🕍', name: 'synagogue' },
			{ emoji: '⛩️', name: 'japanese shrine' },
			{ emoji: '🌉', name: 'bridge at night' },
			{ emoji: '🌃', name: 'night with stars' },
			{ emoji: '🌆', name: 'sunset' },
			{ emoji: '🌇', name: 'sunset' },
			{ emoji: '🌌', name: 'milky way' },
			{ emoji: '🌠', name: 'shooting star' },
			{ emoji: '🎆', name: 'fireworks' },
			{ emoji: '🎇', name: 'sparkler' },
			{ emoji: '🧳', name: 'luggage' },
			{ emoji: '🛂', name: 'passport control' },
			{ emoji: '🛃', name: 'customs' },
			{ emoji: '🛄', name: 'baggage claim' },
			{ emoji: '🛅', name: 'left luggage' },
			{ emoji: '⛽', name: 'fuel pump' },
			{ emoji: '🚏', name: 'bus stop' },
			{ emoji: '🚦', name: 'vertical traffic light' },
			{ emoji: '🚥', name: 'horizontal traffic light' },
			{ emoji: '🚧', name: 'construction' },
		],
	},
	{
		name: 'Objects', icon: '💻',
		emojis: [
			{ emoji: '💻', name: 'laptop' },
			{ emoji: '🖥️', name: 'desktop computer' },
			{ emoji: '🖨️', name: 'printer' },
			{ emoji: '⌨️', name: 'keyboard' },
			{ emoji: '🖱️', name: 'computer mouse' },
			{ emoji: '📱', name: 'mobile phone' },
			{ emoji: '☎️', name: 'telephone' },
			{ emoji: '📞', name: 'telephone receiver' },
			{ emoji: '📺', name: 'television' },
			{ emoji: '📻', name: 'radio' },
			{ emoji: '📷', name: 'camera' },
			{ emoji: '📸', name: 'camera with flash' },
			{ emoji: '📹', name: 'video camera' },
			{ emoji: '🎥', name: 'movie camera' },
			{ emoji: '📡', name: 'satellite antenna' },
			{ emoji: '🔋', name: 'battery' },
			{ emoji: '🔌', name: 'electric plug' },
			{ emoji: '💡', name: 'light bulb' },
			{ emoji: '🔦', name: 'flashlight' },
			{ emoji: '🕯️', name: 'candle' },
			{ emoji: '🧯', name: 'fire extinguisher' },
			{ emoji: '💰', name: 'money bag' },
			{ emoji: '💳', name: 'credit card' },
			{ emoji: '💎', name: 'gem stone' },
			{ emoji: '⚖️', name: 'balance scale' },
			{ emoji: '🔧', name: 'wrench' },
			{ emoji: '🔨', name: 'hammer' },
			{ emoji: '⚒️', name: 'pick' },
			{ emoji: '🛠️', name: 'hammer and wrench' },
			{ emoji: '🔩', name: 'nut and bolt' },
			{ emoji: '🪛', name: 'screwdriver' },
			{ emoji: '🧲', name: 'magnet' },
			{ emoji: '🔪', name: 'kitchen knife' },
			{ emoji: '🛡️', name: 'shield' },
			{ emoji: '🔮', name: 'crystal ball' },
			{ emoji: '🧿', name: 'nazar amulet' },
			{ emoji: '🎨', name: 'artist palette' },
			{ emoji: '🖌️', name: 'paintbrush' },
			{ emoji: '🖍️', name: 'crayon' },
			{ emoji: '✏️', name: 'pencil' },
			{ emoji: '📝', name: 'memo' },
			{ emoji: '📋', name: 'clipboard' },
			{ emoji: '📌', name: 'pushpin' },
			{ emoji: '📍', name: 'round pushpin' },
			{ emoji: '📎', name: 'paperclip' },
			{ emoji: '🖇️', name: 'linked paperclips' },
			{ emoji: '📏', name: 'straight ruler' },
			{ emoji: '📐', name: 'triangular ruler' },
			{ emoji: '✂️', name: 'scissors' },
			{ emoji: '📁', name: 'file folder' },
			{ emoji: '📂', name: 'open file folder' },
			{ emoji: '📓', name: 'notebook' },
			{ emoji: '📔', name: 'notebook with decorative cover' },
			{ emoji: '📒', name: 'ledger' },
			{ emoji: '📕', name: 'closed book' },
			{ emoji: '📗', name: 'green book' },
			{ emoji: '📘', name: 'blue book' },
			{ emoji: '📙', name: 'orange book' },
			{ emoji: '📚', name: 'books' },
			{ emoji: '📖', name: 'open book' },
			{ emoji: '🔖', name: 'bookmark' },
			{ emoji: '🏷️', name: 'label' },
			{ emoji: '🗑️', name: 'wastebasket' },
			{ emoji: '🔒', name: 'locked' },
			{ emoji: '🔓', name: 'unlocked' },
			{ emoji: '🔑', name: 'key' },
			{ emoji: '🗝️', name: 'old key' },
			{ emoji: '🎮', name: 'video game' },
			{ emoji: '🎲', name: 'dice' },
			{ emoji: '♟️', name: 'chess pawn' },
			{ emoji: '🧩', name: 'puzzle piece' },
			{ emoji: '🎯', name: 'direct hit' },
			{ emoji: '🎱', name: 'billiards' },
			{ emoji: '🏆', name: 'trophy' },
			{ emoji: '🥇', name: 'first place medal' },
			{ emoji: '🎭', name: 'performing arts' },
			{ emoji: '🎪', name: 'circus tent' },
			{ emoji: '🎬', name: 'clapper board' },
			{ emoji: '🎤', name: 'microphone' },
			{ emoji: '🎧', name: 'headphone' },
			{ emoji: '🎵', name: 'musical note' },
			{ emoji: '🎶', name: 'musical notes' },
			{ emoji: '🎷', name: 'saxophone' },
			{ emoji: '🎸', name: 'guitar' },
			{ emoji: '🎹', name: 'musical keyboard' },
			{ emoji: '🎺', name: 'trumpet' },
			{ emoji: '🎻', name: 'violin' },
			{ emoji: '🥁', name: 'drum' },
			{ emoji: '🪘', name: 'long drum' },
		],
	},
	{
		name: 'Symbols', icon: '❤️',
		emojis: [
			{ emoji: '❤️', name: 'red heart' },
			{ emoji: '🧡', name: 'orange heart' },
			{ emoji: '💛', name: 'yellow heart' },
			{ emoji: '💚', name: 'green heart' },
			{ emoji: '💙', name: 'blue heart' },
			{ emoji: '💜', name: 'purple heart' },
			{ emoji: '🖤', name: 'black heart' },
			{ emoji: '🤍', name: 'white heart' },
			{ emoji: '🤎', name: 'brown heart' },
			{ emoji: '❤️‍🔥', name: 'heart on fire' },
			{ emoji: '💔', name: 'broken heart' },
			{ emoji: '❣️', name: 'heavy heart exclamation' },
			{ emoji: '💕', name: 'two hearts' },
			{ emoji: '💞', name: 'revolving hearts' },
			{ emoji: '💓', name: 'beating heart' },
			{ emoji: '💗', name: 'growing heart' },
			{ emoji: '💖', name: 'sparkling heart' },
			{ emoji: '💘', name: 'cupid' },
			{ emoji: '💝', name: 'heart with ribbon' },
			{ emoji: '✅', name: 'check mark button' },
			{ emoji: '❌', name: 'cross mark' },
			{ emoji: '⭕', name: 'heavy large circle' },
			{ emoji: '🛑', name: 'stop sign' },
			{ emoji: '⛔', name: 'no entry' },
			{ emoji: '🚫', name: 'prohibited' },
			{ emoji: '💯', name: 'hundred points' },
			{ emoji: '♻️', name: 'recycling symbol' },
			{ emoji: '✔️', name: 'check mark' },
			{ emoji: '❎', name: 'cross mark button' },
			{ emoji: '🔰', name: 'japanese symbol for beginner' },
			{ emoji: '⚡', name: 'high voltage' },
			{ emoji: '🌟', name: 'glowing star' },
			{ emoji: '💫', name: 'dizzy' },
			{ emoji: '✨', name: 'sparkles' },
			{ emoji: '💥', name: 'collision' },
			{ emoji: '❓', name: 'red question mark' },
			{ emoji: '❗', name: 'red exclamation mark' },
			{ emoji: '💤', name: 'sleeping symbol' },
			{ emoji: '🔴', name: 'red circle' },
			{ emoji: '🟠', name: 'orange circle' },
			{ emoji: '🟡', name: 'yellow circle' },
			{ emoji: '🟢', name: 'green circle' },
			{ emoji: '🔵', name: 'blue circle' },
			{ emoji: '🟣', name: 'purple circle' },
			{ emoji: '⚫', name: 'black circle' },
			{ emoji: '⚪', name: 'white circle' },
			{ emoji: '🔶', name: 'large orange diamond' },
			{ emoji: '🔷', name: 'large blue diamond' },
			{ emoji: '🔸', name: 'small orange diamond' },
			{ emoji: '🔹', name: 'small blue diamond' },
			{ emoji: '🔺', name: 'red triangle pointed up' },
			{ emoji: '🔻', name: 'red triangle pointed down' },
			{ emoji: '💠', name: 'diamond shape with a dot inside' },
			{ emoji: '▪️', name: 'black small square' },
			{ emoji: '▫️', name: 'white small square' },
			{ emoji: '◾', name: 'black medium small square' },
			{ emoji: '◽', name: 'white medium small square' },
			{ emoji: '⬛', name: 'black large square' },
			{ emoji: '⬜', name: 'white large square' },
			{ emoji: '🔱', name: 'trident emblem' },
			{ emoji: '📛', name: 'japanese symbol for prohibited' },
			{ emoji: '🎌', name: 'crossed flags' },
			{ emoji: '🏁', name: 'chequered flag' },
			{ emoji: '🚩', name: 'triangular flag' },
			{ emoji: '🎀', name: 'ribbon' },
			{ emoji: '🎗️', name: 'reminder ribbon' },
			{ emoji: '🎟️', name: 'admission tickets' },
			{ emoji: '🎫', name: 'ticket' },
			{ emoji: '☮️', name: 'peace symbol' },
			{ emoji: '✝️', name: 'latin cross' },
			{ emoji: '☪️', name: 'star and crescent' },
			{ emoji: '🕉️', name: 'om' },
			{ emoji: '✡️', name: 'star of david' },
			{ emoji: '☯️', name: 'yin yang' },
			{ emoji: '☦️', name: 'orthodox cross' },
			{ emoji: '🛐', name: 'place of worship' },
			{ emoji: '⛎', name: 'ophiuchus' },
			{ emoji: '♈', name: 'aries' },
			{ emoji: '♉', name: 'taurus' },
			{ emoji: '♊', name: 'gemini' },
			{ emoji: '♋', name: 'cancer' },
			{ emoji: '♌', name: 'leo' },
			{ emoji: '♍', name: 'virgo' },
			{ emoji: '♎', name: 'libra' },
			{ emoji: '♏', name: 'scorpio' },
			{ emoji: '♐', name: 'sagittarius' },
			{ emoji: '♑', name: 'capricorn' },
			{ emoji: '♒', name: 'aquarius' },
			{ emoji: '♓', name: 'pisces' },
		],
	},
]

const search = ref('')
const activeCategory = ref(0)
const searchInput = ref(null)
const emit = defineEmits(['pick', 'close'])

const displayEmojis = computed(() => {
	if (search.value.trim()) {
		// Search across all categories
		const all = []
		for (const cat of categories) all.push(...cat.emojis)
		const query = search.value.toLowerCase()
		return all.filter(item => item.name.includes(query))
	}
	// Show category emojis
	return categories[activeCategory.value]?.emojis ?? []
})

onMounted(() => {
	// Auto-focus search input for better UX
	searchInput.value?.focus()
})
</script>

<template>
	<div class="w-[280px] p-2 flex flex-col gap-1.5 ep-panel" @click.stop @keydown.escape="emit('close')">
		<!-- Category tabs -->
		<div class="flex gap-0.5 flex-wrap" role="tablist" aria-label="Emoji categories">
			<button
				v-for="(cat, i) in categories" :key="cat.name"
				type="button"
				role="tab"
				:aria-selected="activeCategory === i && !search.trim()"
				:aria-label="cat.name"
				class="text-base w-[30px] h-[30px] border-0 bg-transparent rounded-md cursor-pointer transition-colors duration-[120ms] flex items-center justify-center hover:bg-accent/12 focus:outline-offset-0 focus:ring-2 focus:ring-accent"
				:class="{ 'bg-accent/12': activeCategory === i && !search.trim() }"
				:title="cat.name"
				@click="activeCategory = i; search = ''"
				@keydown.arrow-right="activeCategory = Math.min(activeCategory + 1, categories.length - 1)"
				@keydown.arrow-left="activeCategory = Math.max(activeCategory - 1, 0)"
			>{{ cat.icon }}</button>
		</div>

		<!-- Search -->
		<div class="px-0.5">
			<input
				ref="searchInput"
				v-model="search"
				type="text"
				class="w-full py-[5px] px-2 border border-heading/12 rounded-md text-[0.8rem] bg-heading/3 text-text outline-none focus:border-accent"
				placeholder="Search emoji…"
			/>
		</div>

		<!-- Emoji grid -->
		<div class="grid grid-cols-8 gap-px max-h-[200px] overflow-y-auto">
			<button
				v-for="(item, idx) in displayEmojis" :key="`${item.emoji}-${item.name}-${idx}`"
				type="button"
				class="text-[1.2rem] w-[30px] h-[30px] border-0 bg-transparent rounded-[5px] cursor-pointer flex items-center justify-center transition-colors duration-100 p-0 leading-none hover:bg-accent/10"
				:title="item.name"
				@click="emit('pick', item.emoji)"
			>{{ item.emoji }}</button>
		</div>

		<div v-if="displayEmojis.length === 0" class="text-center text-[0.8rem] text-text/40 py-4">No emojis found</div>
	</div>
</template>
